# Configuração base compartilhada entre perfis
spring:
  application:
    name: rpg_market
  
  # Configuração Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  
  # Configuração de Upload de Arquivos
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Configuração do MongoDB padrão (será sobrescrito em produção)
  data:
    mongodb:
      database: Cluster0
      uri: mongodb+srv://admin:batata123@cluster0.clcxyly.mongodb.net/?

server:
  error:
    whitelabel:
      enabled: false

# Configuração do diretório de upload padrão
app:
  upload:
    dir: uploads/images